FROM docker.io/library/ubuntu:jammy

# Remove docker-specific apt configuration
RUN rm /etc/apt/apt.conf.d/docker-gzip-indexes /etc/apt/apt.conf.d/docker-no-languages

# Configure myhostname
RUN sed -Ei 's/^(hosts:.*)(\<files\>)\s*(.*)/\1\2 myhostname \3/' /etc/nsswitch.conf

COPY *-packages /

# Install full set of Ubuntu Server packages (via unminimize) and install packages
RUN sed -Ei '/apt-get (update|upgrade)/s/^/#/' /usr/local/sbin/unminimize && \
  apt-get update && \
  yes | /usr/local/sbin/unminimize && \
  DEBIAN_FRONTEND=noninteractive apt-get -y install \
    ubuntu-minimal ubuntu-standard \
    libnss-myhostname \
    $(cat *-packages | xargs) && \
  rm -rd /var/lib/apt/lists/* && \
  rm /*-packages
