name: Build Base Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 6/12 * * *" # 6am & 6pm every day
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-base-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [22.04]
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      TAGS: ""
      TAGS_CONCAT: ""
      IMAGE_NAME: distrobox-images/base/ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Generate Image Metadata
        if: github.event_name != 'pull_request'
        shell: bash
        run: |
          TAGS=()

          TAGS+=("${IMAGE_REGISTRY}/${IMAGE_NAME}:${{ matrix.version }}")
          TAGS+=("${IMAGE_REGISTRY}/${IMAGE_NAME}:$(git rev-parse --short HEAD)-${{ matrix.version }}")

          echo "TAGS=${TAGS[*]}" >> $GITHUB_ENV
          echo "TAGS_CONCAT=$(IFS=, ; echo "${TAGS[*]}")" >> $GITHUB_ENV

      - name: Generate Image Metadata (Pull Request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          TAGS=()

          TAGS+=("${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:pr${{ github.event.number }}-${{ matrix.version }}")
          TAGS+=("${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:pr${{ github.event.number }}-$(git rev-parse --short HEAD)-${{ matrix.version }}")

          echo "TAGS=${TAGS[*]}" >> $GITHUB_ENV
          echo "TAGS_CONCAT=$(IFS=, ; echo "${TAGS[*]}")" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3

      - name: Build Image
        id: build
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5
        with:
          context: base/ubuntu/${{ matrix.version }}
          file: base/ubuntu/${{ matrix.version }}/Containerfile
          push: true
          tags: ${{ env.TAGS_CONCAT }}


  build-base-alpine:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [3.18]
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      TAGS: ""
      TAGS_CONCAT: ""
      IMAGE_NAME: distrobox-images/base/alpine
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Generate Image Metadata
        if: github.event_name != 'pull_request'
        shell: bash
        run: |
          TAGS=()

          TAGS+=("${IMAGE_REGISTRY}/${IMAGE_NAME}:${{ matrix.version }}")
          TAGS+=("${IMAGE_REGISTRY}/${IMAGE_NAME}:$(git rev-parse --short HEAD)-${{ matrix.version }}")

          echo "TAGS=${TAGS[*]}" >> $GITHUB_ENV
          echo "TAGS_CONCAT=$(IFS=, ; echo "${TAGS[*]}")" >> $GITHUB_ENV

      - name: Generate Image Metadata (Pull Request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          TAGS=()

          TAGS+=("${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:pr${{ github.event.number }}-${{ matrix.version }}")
          TAGS+=("${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:pr${{ github.event.number }}-$(git rev-parse --short HEAD)-${{ matrix.version }}")

          echo "TAGS=${TAGS[*]}" >> $GITHUB_ENV
          echo "TAGS_CONCAT=$(IFS=, ; echo "${TAGS[*]}")" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3

      - name: Build Image
        id: build
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5
        with:
          context: base/alpine/${{ matrix.version }}
          file: base/alpine/${{ matrix.version }}/Containerfile
          push: true
          tags: ${{ env.TAGS_CONCAT }}
